version: '3.8'

services:
  webpage-tracker:
    build: .
    container_name: webpage-tracker
    volumes:
      - ./webpages.xlsx:/app/webpages.xlsx:ro
      - ./webpage_versions:/app/webpage_versions
      - ./diffs:/app/diffs
      - ./logs:/app/logs
    environment:
      - PYTHONUNBUFFERED=1
    command: python webpage_tracker.py
    profiles:
      - tracker

  web-server:
    build: .
    container_name: webpage-web-server
    ports:
      - "8080:8080"
    volumes:
      - ./webpage_versions:/app/webpage_versions:ro
      - ./diffs:/app/diffs:ro
      - ./logs:/app/logs:ro
      - ./web_server.py:/app/web_server.py:ro
    environment:
      - PYTHONUNBUFFERED=1
    command: python web_server.py
    restart: unless-stopped
    profiles:
      - web

  # Combined service that runs both tracker and web server
  webtracker-full:
    build: .
    container_name: webtracker-full
    ports:
      - "8080:8080"
    volumes:
      - ./webpages.xlsx:/app/webpages.xlsx:ro
      - ./webpage_versions:/app/webpage_versions
      - ./diffs:/app/diffs
      - ./logs:/app/logs
      - ./web_server.py:/app/web_server.py:ro
    environment:
      - PYTHONUNBUFFERED=1
    command: >
      sh -c "
        echo 'Starting webpage tracker...' &&
        python webpage_tracker.py &&
        echo 'Starting web server...' &&
        python web_server.py
      "
    restart: unless-stopped

  # Automation service for scheduled runs and Git change detection
  automation:
    build:
      context: .
      dockerfile: automation/Dockerfile.automation
    container_name: webtracker-automation
    volumes:
      - ./webpages.xlsx:/opt/webtracker/webpages.xlsx:ro
      - ./webpage_versions:/opt/webtracker/webpage_versions
      - ./diffs:/opt/webtracker/diffs
      - ./logs:/opt/webtracker/logs
      - ./scripts/auto_update.sh:/opt/webtracker/auto_update.sh:ro
      - ./scripts/morning_tracker.sh:/opt/webtracker/morning_tracker.sh:ro
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=UTC
    restart: unless-stopped
    profiles:
      - automation 