version: '3.8'

services:

  web-server:
    build: .
    container_name: webpage-web-server
    ports:
      - "8080:8080"
    volumes:
      - ./webpage_versions:/app/webpage_versions:ro
      - ./diffs:/app/diffs:ro
      - ./logs:/app/logs:ro
      - ./web_server.py:/app/web_server.py:ro
    environment:
      - PYTHONUNBUFFERED=1
    command: python web_server.py
    restart: unless-stopped
    profiles:
      - web

  # Tracker service (one-time execution)
  tracker:
    build: .
    container_name: webpage-tracker-run
    volumes:
      - ./webpagesv2.xlsx:/app/webpages.xlsx:ro
      - ./webpage_versions:/app/webpage_versions
      - ./diffs:/app/diffs
      - ./logs:/app/logs
    environment:
      - PYTHONUNBUFFERED=1
    command: python webpage_tracker.py
    profiles:
      - tracker

  # Automation service for scheduled runs and Git change detection
  automation:
    build:
      context: .
      dockerfile: automation/Dockerfile.automation
    container_name: webtracker-automation
    volumes:
      - ./webpagesv2.xlsx:/opt/webtracker/webpages.xlsx:ro
      - ./webpage_versions:/opt/webtracker/webpage_versions
      - ./diffs:/opt/webtracker/diffs
      - ./logs:/opt/webtracker/logs
      - ./scripts/auto_update.sh:/opt/webtracker/auto_update.sh:ro
      - ./scripts/morning_tracker.sh:/opt/webtracker/morning_tracker.sh:ro
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=Australia/Sydney
    restart: unless-stopped
    profiles:
      - automation 